apiVersion: v1
kind: Service

metadata:
  name: chattr-backend-service

spec:
  type: {{ .Values.backend.service.type }}

  selector:
    app: chattr-backend

  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}