apiVersion: apps/v1
kind: Deployment

metadata:
  name: chattr-backend

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: chattr-backend

  template:
    metadata:
      labels:
        app: chattr-backend

    spec:
      containers:
        - name: chattr-backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - containerPort: 3000

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}

          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: chattr-backend-config
                  key: NODE_ENV

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: chattr-backend-config
                  key: PORT

            - name: MONGODB_CONNECT
              valueFrom:
                secretKeyRef:
                  name: chattr-backend-secret
                  key: MONGODB_CONNECT

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chattr-backend-secret
                  key: JWT_SECRET