name: Chattr CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Build backend Docker image
        run: docker build -t chattr-backend ./backend

      - name: Build frontend Docker image
        run: docker build -t chattr-frontend ./frontend

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker images
        run: |
          docker tag chattr-backend:latest addy27/chattr-backend:latest
          docker tag chattr-frontend:latest addy27/chattr-frontend:latest

      - name: Push Docker images
        run: |
          docker push addy27/chattr-backend:latest
          docker push addy27/chattr-frontend:latest

          # Docker Hub CI/CD pipeline